# Generated by Django 3.1 on 2020-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='granter',
        ),
        migrations.AddField(
            model_name='wish',
            name='granter',
            field=models.ManyToManyField(related_name='wishes_granted', to='new_app.User'),
        ),
    ]
