# Generated by Django 3.1 on 2020-09-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_wish_liker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='liker',
            new_name='likers',
        ),
    ]
